### ISSUE TITLE
The <?xml ?> tag

### ISSUE THREAD

**Issue by andrew-nemtsev** [colinta/android-xml#1]
Library is NOT include <?xml ?> tag and it results in
"error APT0000: Invalid start tag resource" error
if you are going to use it for Android resource generation.

It's due to xml tag is required.

**Comment by colinta** [comment]
I'd love a PR that fixes this issue, but the last time I used this library I had no trouble using it in an Android project.  Are you using it to generate generic XML?  (it's not meant for that)
